### ISSUE TITLE
M2E generated files should not be under source control

### ISSUE THREAD

**Issue by marioja** [eclipse-aspectj/ajdt#36]
You should add .project, .classpath, .factorypath, .settings **/META-INF/MANIFEST.MF as ignored since these are generated by eclipse and MANIFEST.MF by maven.

You could also add **/META-INF/application.xml and **/META-INF/maven

**Comment by kriegaex** [comment]
Thanks for your suggestion. I inherited the project like this and agree that that kind of content should not be in an SCM. But in a discussion a few years ago with a co-developer I was told that this was done on purpose to get started more easily. We also have an Eclipse IDE specific Maven module "run all tests" in AspectJ, because another developer wants to be able to easily run unit tests across modules from Eclipse instead of Maven.

As for manifests, I actually have not seen the Maven build create or change those. On the contrary, I sometimes need to manually adjust manifest entries when upgrading Eclipse or AspectJ dependencies. As I am a complete noob in OSGI in general and Tycho in particular, I do not want to accidentally destroy anything that I can barely manage to build successfully.

If you wish to become an active AJDT contributor, refactor and fix both the Java and build config content, by all means let us talk about it. I would be happy, if someone would weed out all the bugs and upgrade the heavily outdated code to work better with more recent Eclipse JDT.
